# Generated by Django 4.1.3 on 2022-12-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_answer_answer_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Multiple Choice (1 Correct)'), (1, 'Multiple Choice (Many Correct)')], default=0, verbose_name='Type of Question'),
        ),
    ]
