# Generated by Django 4.1.3 on 2022-12-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
